# Decentralized AI Simulation Configuration
# Environment: development | production
environment: development

# Database Configuration
database:
  path: "ledger.db"
  connection_pool_size: 5
  timeout: 30
  check_same_thread: false

# Simulation Configuration
simulation:
  default_agents: 50
  default_steps: 100
  grid_width: 10
  grid_height: 10
  step_delay: 0.1
  anomaly_rate: 0.05
  use_parallel_threshold: 50

# Agent Configuration
agent:
  initial_wealth: 1
  initial_trust_score: 100
  trust_increment: 10
  trust_decrement: 20
  blacklist_threshold: 50
  trade_probability: 0.1
  move_probability: 0.5

# Logging Configuration
logging:
  level: "INFO"
  file: "simulation.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Streamlit Dashboard Configuration
streamlit:
  page_title: "Decentralized AI Simulation"
  layout: "wide"
  agent_slider_min: 10
  agent_slider_max: 200
  agent_slider_default: 50
  anomaly_slider_min: 0.0
  anomaly_slider_max: 0.1
  anomaly_slider_default: 0.05
  steps_slider_min: 10
  steps_slider_max: 100
  steps_slider_default: 50
  cache_ttl: 5

# Monitoring Configuration
monitoring:
  health_check_interval: 30
  metrics_port: 8000
  enable_prometheus: false
  enable_detailed_metrics: true
  metrics_retention_days: 7

# Performance Configuration
performance:
  enable_multiprocessing: true
  max_workers: 4
  memory_limit_mb: 1024
  gc_threshold: 1000

# Security Configuration
security:
  enable_input_validation: true
  max_request_size_mb: 10
  rate_limit_requests_per_minute: 100

# Development Configuration
development:
  debug_mode: false
  enable_profiling: false
  log_sql_queries: false
  auto_reload: false